#!/bin/bash

# path to repo
NOTESPATH=/home/gdobbe/Notes
# today's filename
FILE=$(date +%m-%d)-notes
YEAR=$(date +%Y)
MONTH=$(date +%m)

# look for a file matching the pattern of mm-dd-notes
if [ ! -f $NOTESPATH/$YEAR/$MONTH/$FILE ]; then
    # if it doesn't exist, create it.
    echo "No file for today. Creating."
    touch $NOTESPATH/$YEAR/$MONTH/$FILE
fi
# open that file
geany $NOTESPATH/$YEAR/$MONTH/$FILE &
# exit gracefully.
