#!/bin/bash

source $HOME/.nsrc

# SETTINGS!
GIT=`which git`                         # some systems have problems with identifying where git is

# first, import the ssh key because cron and variable scope and all that
ssh-agent bash -c 'ssh-add '$SSH_KEY    

# switch to the notes repo
cd $REPODIR

# have flashbake commit the repo
/usr/local/bin/flashbake $REPODIR 
# then, pull from remote 
${GIT} pull origin master
# then push!
${GIT} push origin master
