#!/bin/bash
source $HOME/.nsrc

# today's filename, along with simple numbers for the year and month direcotries
FILE=$(date +%m-%d)-notes
YEAR=$(date +%Y)
MONTH=$(date +%m)

if [[ $* == *--yesterday* ]]; then
	FILE=$(date -d yesterday +%m-%d)-notes
	YEAR=$(date -d yesterday +%Y)
	MONTH=$(date -d yesterday +%m)
	echo "Opening yesterday's notes."
# look for a file matching the pattern of mm-dd-notes

elif [ ! -f $REPODIR/$YEAR/$MONTH/$FILE ]; then
	# also check for the directory.
	if [ ! -d $REPODIR/$YEAR/$MONTH/ ]; then
		# if the directory doesn't exist, create it first using the recursive method.
		mkdir -p $REPODIR/$YEAR/$MONTH
	fi
	# if the file doesn't exist, create it.
    echo "No file for today. Creating."
    touch $REPODIR/$YEAR/$MONTH/$FILE
fi
# then, open that file in the background with our trusty editor
${EDITOR} $REPODIR/$YEAR/$MONTH/$FILE &
